// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNurse(ctx context.Context, arg CreateNurseParams) (Nurse, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyRecord(ctx context.Context, arg CreateVerifyRecordParams) (EmailVerification, error)
	CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error)
	GetNurse(ctx context.Context, userID uuid.UUID) (Nurse, error)
	GetPatient(ctx context.Context, userID uuid.UUID) (Patient, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetVerifyRecord(ctx context.Context, arg GetVerifyRecordParams) (EmailVerification, error)
	UpdateVerifyRecordAttempt(ctx context.Context, verificationID uuid.UUID) (EmailVerification, error)
	UpdateVerifyRecordInvalid(ctx context.Context, verificationID uuid.UUID) (EmailVerification, error)
}

var _ Querier = (*Queries)(nil)
